name: Deploy Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: NODE_ENV=production npm run build
      - run: npx surge ./public ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      - run: npx surge ./public ${{ secrets.WEBSITE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
